# Generated by Django 2.2.4 on 2020-12-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201127_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selectedDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selectedTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
