# Generated by Django 2.2.4 on 2020-12-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201203_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='selectedDate',
            new_name='selected_date',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='selectedTime',
            new_name='selected_time',
        ),
    ]
