# Generated by Django 2.2.4 on 2021-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210102_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('A', 'Available'), ('S', 'Sold Out'), ('P', 'Pre-order')], max_length=1),
        ),
    ]
