# Generated by Django 2.2.4 on 2021-01-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210104_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tights'), ('S', 'Shorts'), ('TB', 'Top Bras')], max_length=2),
        ),
    ]
